name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install -r src/requirements.txt  # You may replace this with the actual dependencies installation command

    - name: Change to src directory
      run: cd src

    - name: Run Tests
      run: ./test.sh
